apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "imap2telegram.labels" . | nindent 4 }}
data:
  settings.py: |

    from urllib.parse import urlparse

    LOG_LEVEL = "{{ .Values.logLevel }}"

    SEND_ONLY_ATTACHMENT = {{ .Values.sendOnlyAttachment | toString | title }}

    IMAP_HOST = "{{ .Values.imapHost }}"
    IMAP_USER = "{{ .Values.imapUser }}"
    IMAP_PASSWORD = '{{ .Values.imapPassword }}'

    TELEGRAM_USER_IDS = [{{ range .Values.telegramIDS }}"{{ . }}", {{ end }}]
    TELEGRAM_TOKEN = "{{ .Values.telegramToken }}"

    NTFY_URL = "{{ .Values.ntfyURL }}"
    NTFY_TOKEN = "{{ .Values.ntfyToken }}"
    NTFY_TAGS = "{{ .Values.ntfyTags }}"
    NTFY_PRIORITY = "{{ .Values.ntfyPriority }}"

    NTFY_MARKDOWN = "{{ .Values.ntfyMarkdown }}"

    NTFY_TOPIC = urlparse(NTFY_URL).path.strip("/")

