apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "imap2telegram.labels" . | nindent 4 }}
data:
  settings.py: |

    LOG_LEVEL = "{{ .Values.logLevel }}"

    IMAP_HOST = "{{ .Values.imapHost }}"
    IMAP_USER = "{{ .Values.imapUser }}"
    IMAP_PASSWORD = '{{ .Values.imapPassword }}'

    TELEGRAM_USER_IDS = [{{ range .Values.telegramIDS }}"{{ . }}", {{ end }}]
    TELEGRAM_TOKEN = "{{ .Values.telegramToken }}"
    TELEGRAM_ATTACH = {{ print .Values.telegramAttach | title }}

    NTFY_URL = {{ .Values.ntfyURL }}
    NTFY_TOKEN = {{ .Values.ntfyToken }}
    NTFY_TAGS = {{ .Values.ntfyTags }}
    NTFY_PRIORITY = {{ .Values.ntfyPriority }}
